version: '3.8'
services:
  # Dedicated Database for Kisan Sahayak
  kisan-db:
    image: postgres:15
    container_name: kisan-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432" # We use 5435 to avoid conflict with your other project
    volumes:
      - kisan_data:/var/lib/postgresql/data

  # Caching Layer for Kisan Sahayak
  kisan-redis:
    image: redis:7-alpine
    container_name: kisan-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  kisan_data: