version: '3.8'
services:
  kisan-db:
    image: postgres:15
    container_name: kisan-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kisan_pass
      - POSTGRES_DB=kisan_db
    ports:
      - "5433:5432" # Mapping to 5433 to avoid conflict with your other project
    volumes:
      - kisan_pg_data:/var/lib/postgresql/data

volumes:
  kisan_pg_data:
  